# Generated by Django 4.1.1 on 2022-10-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='200', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='200', editable=False, null=True),
        ),
    ]
